import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useMoralis } from "react-moralis";
import Login from "../components/Login";
import Header from "../components/Header";
import Messages from "../components/Messages";

export default function Home() {
  const { isAuthenticated } = useMoralis();

  if (!isAuthenticated) return <Login />;
  return (
    <div className=" h-screen bg-gradient-to-b overflow-y-scroll from-black to-fuchsia-900 overflow-hidden scrollbar-hide">
      <Head>
        <title>MataVerse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-screen-xl mx-auto ">
        <Header />
        <Messages />
      </div>
    </div>
  );
}
